apiVersion: apps/v1
kind: Deployment
metadata:
  name: consequence-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consequenceservice
  template:
    metadata:
      labels:
        app: consequenceservice
    spec:
      containers:
      - name: consequenceservice
        image: rolandpark/consequenceservice:latest