apiVersion: apps/v1
kind: Deployment
metadata:
  name: consequence-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consequenceservice
  template:
    metadata:
      labels:
        app: consequenceservice
    spec:
      containers:
      - name: consequenceservice
        image: rolandpark/consequenceservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: consequence-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: consequenceservice
  ports:
  - port: 80
    name: consequenceservice
    protocol: TCP
    targetPort: 80
