apiVersion: apps/v1
kind: Deployment
metadata:
  name: mood-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodservice
  template:
    metadata:
      labels:
        app: moodservice
    spec:
      containers:
      - name: moodservice
        image: rolandpark/moodservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mood-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: moodservice
  ports:
  - port: 80
    name: moodservice
    protocol: TCP
    targetPort: 80
