apiVersion: apps/v1
kind: Deployment
metadata:
  name: mood-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodservice
  template:
    metadata:
      labels:
        app: moodservice
    spec:
      containers:
      - name: moodservice
        image: rolandpark/moodservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: mood-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: moodservice
  ports:
  - port: 80
    targetPort: 80
