apiVersion: apps/v1
kind: Deployment
metadata:
  name: reaction-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactionservice
  template:
    metadata:
      labels:
        app: reactionservice
    spec:
      containers:
      - name: reactionservice
        image: rolandpark/reactionservice:latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        # ports:
        # - containerPort: <Port>
---
apiVersion: v1
kind: Service
metadata:
  name: reaction-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: reactionservice
  ports:
  - port: 80
    targetPort: 80
