apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: galactusui
  template:
    metadata:
      labels:
        app: galactusui
    spec:
      containers:
      - name: galactusui
        image: rolandpark/galactusui:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ui-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: galactusui
  ports:
  - port: 80
    name: galactusui
    protocol: TCP
    targetPort: 80
